sudo: false
language: node_js
node_js:
  - 12 # use nodejs v12 LTS
cache: npm
branches:
  only:
    - src # build src branch only
script:
  - git clone https://github.com/theme-next/hexo-theme-next themes/next
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: src
  local-dir: public
  target_branch: master